### ISSUE TITLE
datepicker defaultdate

### ISSUE THREAD

**Issue by alfred-c** [jquery-ui-bootstrap/jquery-ui-bootstrap#114]
a style is needed for .ui-datepicker td .ui-state-highlight
should be similar to .ui-datepicker td .ui-state-active

**Comment by addyosmani** [comment]
Thanks. We'll take a look at this.

**Comment by gtraxx** [comment]
The bug is fixed :)

I can close this issue ?

**Comment by addyosmani** [comment]
Please feel free to close any bugs you feel are fixed :)

**Comment by gtraxx** [comment]
okay :)

**Comment by camilosw** [comment]
Where is the css with the .ui-datepicker td .ui-state-highlight? I can't find it. I think this bug is not fixed.

**Comment by gtraxx** [comment]
view issue #170
